# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u6807\u9898')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('requirement', models.TextField(verbose_name='\u8981\u6c42')),
                ('responsibility', models.TextField(verbose_name='\u804c\u8d23')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('tag', models.TextField(verbose_name='\u6807\u7b7e')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Address', verbose_name='\u5730\u5740')),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Assortment', verbose_name='\u62db\u8058\u5206\u7c7b')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Category', verbose_name='\u6280\u672f\u5206\u7c7b')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Department', verbose_name='\u90e8\u95e8')),
            ],
        ),
    ]
